name: NABR automation - Smoke suite
description: Runs smoke suite
on:
  schedule:
    - cron: "30 10 * * 5"
inputs:
  showroom-stage-url:
    description: The showroom stage URL.
    required: false
    default: https://showroom.nabr.devhive.net
  showroom-gateway-stage-url:
    description: The showroom gateway stage URL.
    required: true
    default: https://showroom-gateway.nabr.devhive.net
jobs:
  test:
    name: Run smoke test
    timeout-minutes: 60
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
        with:
          node-version: "14.x"
      - name: Install dependencies
        run: npm ci
      - name: Install Playwright Browsers
        run: npx playwright install --with-deps
      - name: Run smoke test
        run: npx playwright test
        env:
        SHOWROOM_STAGE_URL: ${{ inputs.showroom-stage-url }}
        SHOWROOM_GATEWAY_URL: ${{ inputs.showroom-gateway-stage-url }}
      - uses: actions/upload-artifact@v2
        if: always()
        with:
          name: playwright-report
          path: playwright-report/
          retention-days: 30
